#!/bin/bash

rover graph introspect https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-congress | rover graph publish simple-servers2@congress --schema - --profile prod-gh 
rover graph introspect https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-address-enrichment | rover graph publish simple-servers2@address-enrichment --schema - --profile prod-gh 
rover graph introspect https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-ip-enrichment | rover graph publish simple-servers2@ip-enrichment --schema - --profile prod-gh 
rover graph introspect https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-daylight | rover graph publish simple-servers2@daylight --schema - --profile prod-gh 
rover graph introspect https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-weather | rover graph publish simple-servers2@weather --schema - --profile prod-gh 
rover graph introspect https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-astronomy | rover graph publish simple-servers2@astronomy --schema - --profile prod-gh 

rover subgraph introspect https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-congress | rover subgraph publish congress2@main --name congress --schema - --routing-url https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-congress --profile prod-gh 
rover subgraph introspect https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-address-enrichment | rover subgraph publish congress2@main --name address-enrichment --schema - --routing-url https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-address-enrichment --profile prod-gh 
rover subgraph introspect https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-ip-enrichment | rover subgraph publish congress2@main --name ip-enrichment --schema - --routing-url https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-ip-enrichment --profile prod-gh 
rover subgraph introspect https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-daylight | rover subgraph publish congress2@main --name daylight --schema - --routing-url https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-daylight --profile prod-gh 
rover subgraph introspect https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-weather | rover subgraph publish congress2@main --name weather --schema - --routing-url https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-weather --profile prod-gh 
rover subgraph introspect https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-astronomy | rover subgraph publish congress2@main --name astronomy --schema - --routing-url https://simple-graphql-servers.netlify.app/.netlify/functions/subgraph-astronomy --profile prod-gh 